FROM kalilinux/kali-linux-docker:latest

ENV ANSIBLE_VAULT_PASSWORD_FILE .vault_env
ENV ANSIBLE_VAULT_PASSWORD

RUN apt-get update && apt-get dist-upgrade -y

RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip

RUN python3 -m pip install -U pip ansible

ENTRYPOINT ["/sbin/init"]